import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/theme";
import { ClerkProvider } from "@clerk/nextjs";
import { connectMongoDB } from "@/config/mongodb";
import CustomLayout from "@/custom-layouts";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CarePulse",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  await connectMongoDB()
  return (
  <ClerkProvider>
      <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <CustomLayout>
          {children}
          </CustomLayout>
        </ThemeProvider>
      </body>
    </html>
  </ClerkProvider>
  );
}
